import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import '../../providers/book_provider.dart';
import '../../models/book_model.dart';
import '../../core/theme/card_styles.dart';

class AddBookScreen extends StatefulWidget {
  final BookModel? bookToEdit;

  const AddBookScreen({super.key, this.bookToEdit});

  @override
  State<AddBookScreen> createState() => _AddBookScreenState();
}

class _AddBookScreenState extends State<AddBookScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _authorController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _coverImageUrlController = TextEditingController();
  final _pdfUrlController = TextEditingController();
  final _tagsController = TextEditingController();

  String _selectedCategory = 'Fiction';
  String _selectedLanguage = 'English';
  bool _isLoading = false;
  bool _isEditMode = false;
  bool _isPremiumOnly = false;
  bool _isFree = true;

  final List<String> _categories = [
    'Fiction',
    'Non-Fiction',
    'Science',
    'Technology',
    'History',
    'Biography',
    'Self-Help',
    'Business',
    'Romance',
    'Mystery',
    'Fantasy',
    'Horror',
    'Adventure',
    'Educational',
    'Programming',
    'Design',
    'Art',
    'Psychology',
    'Philosophy',
    'Health',
  ];

  final List<String> _languages = [
    'English',
    'Indonesian',
    'Spanish',
    'French',
    'German',
    'Chinese',
    'Japanese',
    'Arabic',
  ];

  @override
  void initState() {
    super.initState();
    _isEditMode = widget.bookToEdit != null;

    if (_isEditMode) {
      _populateFieldsForEdit();
    }
  }

  void _populateFieldsForEdit() {
    final book = widget.bookToEdit!;
    _titleController.text = book.title;
    _authorController.text = book.author;
    _descriptionController.text = book.description;
    _coverImageUrlController.text = book.coverImageUrl;
    _pdfUrlController.text = book.fileUrl;
    _tagsController.text = book.tags.join(', ');

    _selectedCategory = book.category;
    _selectedLanguage = book.language;
    _isPremiumOnly = book.isPremiumOnly;
    _isFree = book.isFree;
  }

  @override
  void dispose() {
    _titleController.dispose();
    _authorController.dispose();
    _descriptionController.dispose();
    _coverImageUrlController.dispose();
    _pdfUrlController.dispose();
    _tagsController.dispose();
    super.dispose();
  }

  Future<void> _saveBook() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final bookProvider = Provider.of<BookProvider>(context, listen: false);

      final tags = _tagsController.text
          .split(',')
          .map((tag) => tag.trim())
          .where((tag) => tag.isNotEmpty)
          .toList();

      if (_isEditMode) {
        // Update existing book
        final updatedBook = widget.bookToEdit!.copyWith(
          title: _titleController.text.trim(),
          author: _authorController.text.trim(),
          description: _descriptionController.text.trim(),
          category: _selectedCategory,
          coverImageUrl: _coverImageUrlController.text.trim(),
          fileUrl: _pdfUrlController.text.trim(),
          language: _selectedLanguage,
          tags: tags,
          isFree: _isFree,
          isPremiumOnly: _isPremiumOnly,
        );

        await bookProvider.updateBook(
          bookId: widget.bookToEdit!.id,
          updatedBook: updatedBook,
        );
        _showSnackBar('Buku berhasil diperbarui!');
      } else {
        // Create new book
        final newBook = BookModel(
          id: '', // Will be generated by BookProvider
          title: _titleController.text.trim(),
          author: _authorController.text.trim(),
          description: _descriptionController.text.trim(),
          category: _selectedCategory,
          coverImageUrl: _coverImageUrlController.text.trim(),
          fileUrl: _pdfUrlController.text.trim(),
          publishedDate: DateTime.now(),
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
          language: _selectedLanguage,
          tags: tags,
          isFree: _isFree,
          isPremiumOnly: _isPremiumOnly,
        );

        await bookProvider.addBookDirectly(newBook);
        _showSnackBar('Buku berhasil ditambahkan!');
      }

      if (mounted) {
        context.pop();
      }
    } catch (e) {
      _showSnackBar('Error saat menyimpan buku: $e', isError: true);
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  void _showSnackBar(String message, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? Colors.red : Colors.green,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        backgroundColor: theme.appBarTheme.backgroundColor,
        title: Text(_isEditMode ? 'Edit Buku' : 'Tambah Buku'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.pop(),
        ),
        actions: [
          if (_isLoading)
            const Padding(
              padding: EdgeInsets.all(16.0),
              child: SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(strokeWidth: 2),
              ),
            )
          else
              TextButton(
              onPressed: _saveBook,
              child: Text(_isEditMode ? 'Perbarui' : 'Simpan'),
            ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Basic Information Section
              Container(
                padding: const EdgeInsets.all(20),
                decoration: CardStyles.modernCard(
                  theme.brightness == Brightness.dark,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Informasi Dasar',
                      style: theme.textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),

                    // Title
                    TextFormField(
                      controller: _titleController,
                      decoration: const InputDecoration(
                        labelText: 'Judul Buku *',
                        hintText: 'Masukkan judul buku',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Silakan masukkan judul buku';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),

                    // Author
                    TextFormField(
                      controller: _authorController,
                      decoration: const InputDecoration(
                        labelText: 'Penulis *',
                        hintText: 'Masukkan nama penulis',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Silakan masukkan nama penulis';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),

                    // Description
                    TextFormField(
                      controller: _descriptionController,
                      maxLines: 4,
                      decoration: const InputDecoration(
                        labelText: 'Deskripsi *',
                        hintText: 'Masukkan deskripsi buku',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Silakan masukkan deskripsi buku';
                        }
                        return null;
                      },
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 16),

              // Media URLs Section
              Container(
                padding: const EdgeInsets.all(20),
                decoration: CardStyles.modernCard(
                  theme.brightness == Brightness.dark,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'URL Media',
                      style: theme.textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),

                    // Cover Image URL
                    TextFormField(
                      controller: _coverImageUrlController,
                      decoration: const InputDecoration(
                        labelText: 'URL Gambar Cover *',
                        hintText: 'https://example.com/cover.jpg',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.image),
                      ),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Silakan masukkan URL gambar cover';
                        }
                        final uri = Uri.tryParse(value);
                        if (uri == null || !uri.hasAbsolutePath) {
                          return 'Silakan masukkan URL yang valid';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),

                    // PDF URL
                    TextFormField(
                      controller: _pdfUrlController,
                      decoration: const InputDecoration(
                        labelText: 'URL File PDF *',
                        hintText: 'https://example.com/book.pdf',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.picture_as_pdf),
                      ),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Silakan masukkan URL file PDF';
                        }
                        final uri = Uri.tryParse(value);
                        if (uri == null || !uri.hasAbsolutePath) {
                          return 'Silakan masukkan URL yang valid';
                        }
                        return null;
                      },
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 16),

              // Category and Settings Section
              Container(
                padding: const EdgeInsets.all(20),
                decoration: CardStyles.modernCard(
                  theme.brightness == Brightness.dark,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Kategori & Pengaturan',
                      style: theme.textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),

                    // Category Dropdown
                    DropdownButtonFormField<String>(
                      value: _selectedCategory,
                      decoration: const InputDecoration(
                        labelText: 'Kategori',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.category),
                      ),
                      items: _categories.map((category) {
                        return DropdownMenuItem(
                          value: category,
                          child: Text(category),
                        );
                      }).toList(),
                      onChanged: (value) {
                        setState(() {
                          _selectedCategory = value!;
                        });
                      },
                    ),
                    const SizedBox(height: 16),

                    // Language Dropdown
                    DropdownButtonFormField<String>(
                      value: _selectedLanguage,
                      decoration: const InputDecoration(
                        labelText: 'Bahasa',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.language),
                      ),
                      items: _languages.map((language) {
                        return DropdownMenuItem(
                          value: language,
                          child: Text(language),
                        );
                      }).toList(),
                      onChanged: (value) {
                        setState(() {
                          _selectedLanguage = value!;
                        });
                      },
                    ),
                    const SizedBox(height: 16),

                    // Tags
                    TextFormField(
                      controller: _tagsController,
                      decoration: const InputDecoration(
                        labelText: 'Tag (Opsional)',
                        hintText: 'programming, tutorial, beginner',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.tag),
                        helperText: 'Pisahkan tag dengan koma',
                      ),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 16),

              // Access Control Section
              Container(
                padding: const EdgeInsets.all(20),
                decoration: CardStyles.modernCard(
                  theme.brightness == Brightness.dark,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(
                          Icons.lock_outline,
                          color: theme.colorScheme.primary,
                          size: 24,
                        ),
                        const SizedBox(width: 8),
                        Text(
                          'Kontrol Akses',
                          style: theme.textTheme.titleLarge?.copyWith(
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Text(
                      'Atur siapa yang dapat mengakses buku ini',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: theme.colorScheme.onSurface.withOpacity(0.6),
                      ),
                    ),
                    const SizedBox(height: 20),

                    // Premium Only Switch
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: _isPremiumOnly
                            ? theme.colorScheme.primaryContainer.withOpacity(0.3)
                            : theme.colorScheme.surfaceVariant.withOpacity(0.3),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: _isPremiumOnly
                              ? theme.colorScheme.primary.withOpacity(0.5)
                              : theme.colorScheme.outline.withOpacity(0.3),
                          width: 1.5,
                        ),
                      ),
                      child: Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(8),
                            decoration: BoxDecoration(
                              color: _isPremiumOnly
                                  ? theme.colorScheme.primary.withOpacity(0.2)
                                  : theme.colorScheme.surfaceVariant,
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: Icon(
                              Icons.workspace_premium,
                              color: _isPremiumOnly
                                  ? theme.colorScheme.primary
                                  : theme.colorScheme.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'Buku Premium',
                                  style: theme.textTheme.titleMedium?.copyWith(
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                const SizedBox(height: 4),
                                Text(
                                  _isPremiumOnly
                                      ? 'Hanya pengguna premium yang dapat mengakses'
                                      : 'Semua pengguna dapat mengakses buku ini',
                                  style: theme.textTheme.bodySmall?.copyWith(
                                    color: theme.colorScheme.onSurface
                                        .withOpacity(0.7),
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Switch(
                            value: _isPremiumOnly,
                            onChanged: (value) {
                              setState(() {
                                _isPremiumOnly = value;
                                if (value) {
                                  _isFree = false; // Premium books are not free
                                } else {
                                  _isFree = true; // Non-premium books are free by default
                                }
                              });
                            },
                          ),
                        ],
                      ),
                    ),

                    const SizedBox(height: 16),

                    // Information Card
                    Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: theme.colorScheme.surfaceVariant.withOpacity(0.3),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Row(
                        children: [
                          Icon(
                            Icons.info_outline,
                            size: 20,
                            color: theme.colorScheme.onSurfaceVariant,
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Text(
                              _isPremiumOnly
                                  ? 'Buku ini akan ditandai sebagai PREMIUM. Pengguna harus berlangganan untuk mengaksesnya.'
                                  : 'Buku ini akan ditandai sebagai FREE. Semua pengguna dapat mengaksesnya tanpa berlangganan.',
                              style: theme.textTheme.bodySmall?.copyWith(
                                color: theme.colorScheme.onSurfaceVariant,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 32),

              // Save Button for Mobile
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                  onPressed: _isLoading ? null : _saveBook,
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            valueColor: AlwaysStoppedAnimation<Color>(
                              Colors.white,
                            ),
                          ),
                        )
                      : Text(_isEditMode ? 'Perbarui Buku' : 'Tambah Buku'),
                ),
              ),

              const SizedBox(height: 16),
            ],
          ),
        ),
      ),
    );
  }
}
